### ISSUE TITLE
Add support for iOS

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#1]
As I only have an Android device I haven't been able to test iOS support.

We'll need the following:
- A [native adaptor module](https://facebook.github.io/react-native/docs/native-modules-android.html#content) to expose URL discovery to JS runtime.
  - It might make sense to move as much logic as possible into JS so that adaptors stay slim and we don't have duplicate logic in Java and Objective-C.
- Abstractions around Android only components (eg. `ProgressBarAndroid`)

+@etiennesegonzac

**Comment by wilsonpage** [comment]
> It might make sense to move as much logic as possible into JS so that adaptors stay slim and we don't have duplicate logic in Java and Objective-C.

This has landed. Now all the Objective-C adaptor needs to do is expose the advertised bytes and rssi value to JS. I'm assuming the advertisement will be in the same format as Android (`Int8Array`), if we'll need to convert it before sending over to JS.

**Comment by wilsonpage** [comment]
Ettienne's [magnet-ios](https://github.com/mozilla-magnet/magnet-ios) client should provide all we need  to implement this.

**Comment by arcturus** [comment]
Will try to have something ready. Just asked for an iphone ;)

**Comment by wilsonpage** [comment]
FYI Emily said we can borrow devices off her

**Comment by arcturus** [comment]
\o/
