### ISSUE TITLE
Web page not available error shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#108]
_From @isabelrios on May 24, 2016 10:41_

I have to investigate the steps to reproduce this, in case it is reproducible. So far I have seen it only once.
The problem is that although I refreshed the app it was not solved, I had to close it and open it again so that I got the tile correclty shown.
I was playing with the app removing the tiles by swaping right, updating the app, check behaviour when there is not internet connection and so when the error appeared.
![screenshot_2016-05-24-12-28-58](https://cloud.githubusercontent.com/assets/1897507/15501234/c4687ff2-21ac-11e6-8137-e43fe81c2d43.png)

Will update when having more info but thought it was important to comment.

_Copied from original issue: mozilla-magnet/magnet-adaptor-sched#17_

**Comment by wilsonpage** [comment]
This could be related to #106. Does the tile fail straight away or timeout after some time showing the loading spinner?

**Comment by isabelrios** [comment]
Sorry I could not tell you, I did not realized exactly when it happened...I saw it when I open the app, have to investigate further to see when it appears.

**Comment by wilsonpage** [comment]
No longer valid with new design
