### ISSUE TITLE
Provide downloadable builds for Android

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#11]
We should provide APKs (and iOS equivalent) for anyone who wishes to try out Magnet. Ideally we would have builds tied to official releases as well as nightly unstable builds.

@samgiles to add more detail, and perhaps take up :)

**Comment by samgiles** [comment]
#23

**Comment by samgiles** [comment]
It works \o/:
https://github.com/mozilla-magnet/magnet/releases
