### ISSUE TITLE
No connection error message if the connection is lost while the app is open

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#110]
Not a critical issue but is important from a user point of view to keep him correctly informed.
The same way there is an error when opening the app when the wifi is off: 'Network error, please check your internet connection'. 
There should be some kind of warning to let user know that the connection is lost if he tries to refresh the app when the connection is off for some reason.

**Comment by isabelrios** [comment]
Network error appears now when the app is open and the connection is lost.
Closing this.

**Comment by wilsonpage** [comment]
@isabelrios I don't quite follow. Are you saying that this is not longer an issue?

**Comment by isabelrios** [comment]
@wilsonpage I closed it because now I can see that connection error message when the app is open and the connection is lost. It was not shown before, only when the connection was off and you tried to open the app the message appeared. 
I was surprised it was showed today since I have not seen changes on that...but it is now there...

**Comment by wilsonpage** [comment]
@isabelrios there is a bug then? If so, is it being tracked?

**Comment by isabelrios** [comment]
@wilsonpage, No, there is not any bug about this now, this is working fine :)
