### ISSUE TITLE
Tie pull-to-refresh indicatior to header-bar loading indicator

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#112]
We still have the native RefreshControl to indicate the pull-to-refresh state. Although this doesn't work too well as it sit underneath the header-bar.

We need a way to tie the negative 'overscroll' position to the blue loading indicator in the header-bar.

This is fairly simple in iOS, but Android seems not to have a way of detecting 'overscroll'. This may mean we need to add some functionality to ReactScrollView to send us the require events.

**Comment by isabelrios** [comment]
@wilsonpage I was going to open an issue because just realized that when having several tiles, more than 7-8, and you are at the bottom, you have to scroll all up to update the app and then scroll all down to see the new tiles. It is not very friendly having to do that to see the new tiles. 
Not sure if this issue would solve that or should I open a new one?
Thanks!

**Comment by wilsonpage** [comment]
Interesting. Now we have the app-header with logo, we could follow the convention of tapping the logo to scroll to top. Also once #98 has been implemented, the order of tiles should be more intuitive.

**Comment by wilsonpage** [comment]
Generally ,the pull-to-refresh interaction shouldn't be used that much. While the app is open we should be scanning frequently enough that the user isn't forced to perform a scan manually. I think personally the pull-to-refresh would work better as a 'clear everything and start fresh' intent.

**Comment by isabelrios** [comment]
Yeah, that could be a good idea, tapping on the logo to scroll to top. 
For the testing I use the pull-to-refresh a lot for having the tiles updates after changing the beacons url without waiting, but I agree that on a real use it would not be that frequently used.

**Comment by wilsonpage** [comment]
This polish isn't required for our MVP.
