### ISSUE TITLE
Tile is shown more transparent than it should

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#117]
This has happened to me a few times. The tile is shown with less intensity (see Mozilla tile below). It does not change to the regular view till the app is closed and open again.
It works tapping on the tile to open the web page, but the feeling when using the app could be that it is not available.
![screenshot_2016-05-31-09-38-56](https://cloud.githubusercontent.com/assets/1897507/15703270/a319c61a-27e4-11e6-81c4-4a4b7ff6868f.png)

**Comment by wilsonpage** [comment]
I've seen this too. I believe it's related to a react-native Android bug in [`LayoutAnimation`](http://facebook.github.io/react-native/releases/0.26/docs/layoutanimation.html#layoutanimation)s. A simple fix would be to prevent opacity transition when a new tile is rendered, leaving just the `XY` transition. Or we could remove the `LayoutAnimation` on list items altogether.

**Comment by wilsonpage** [comment]
This was a bug with ReactNative 'LayoutAnimation' on Android. I've removed the opacity property from the layout animation, so this issue should be resolved.

I'm hoping when we update to a newer release this will be fixed.
