### ISSUE TITLE
Provide visual feedback when performing the scan.

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-client#13]
Right now we have an empty string while we are doing the scanning. Sometimes I think something is broken ;D

**Comment by wilsonpage** [comment]
Good call. We should have some text or a spinner.

**Comment by arcturus** [comment]
Related, but not just providing feedback:

https://github.com/jsdf/react-native-refreshable-listview

A component that implements a 'virtual list' , as you already implemented in firefox that also comes with the pull to refresh :)

**Comment by oteo** [comment]
It could be related or perhaps can be done to Add pull to refresh task (issue 24)

**Comment by wilsonpage** [comment]
Agreed, closing and bundling as part of #24.
