### ISSUE TITLE
Should the menu button be 'deactivated' till having content available?

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#131]
Hi, @arcturus, @wilsonpage, Are we planning to add content to the app menu for London? 
If there will not be any content avaialable I would say to deactivate it or I do not know what we could do but currently you can tap on it and see how it changes but nothing is shown, so it could seem that it is not working.

Same for the button in the tile view.

What do you think? 
Thanks!

**Comment by wilsonpage** [comment]
Agreed, this button should be hidden.

**Comment by samgiles** [comment]
Just made a PR for this: #133

**Comment by samgiles** [comment]
Closed in #133

**Comment by isabelrios** [comment]
@wilsonpage @samgiles I mentioned it in the first comment but was not very clear, sorry about that, I think we should do the same for the more button in the tile expanded view.

**Comment by isabelrios** [comment]
I will create a PR for that

**Comment by samgiles** [comment]
Sorry I shouldn't have closed, I completely missed the stuff about the expanded view button, my fault.
