### ISSUE TITLE
Tiles are not updated

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#140]
This has been seen with sched but affects all urls that would change the content.
The tile is not automatically updated, not even forcing the app by pulling down to refresh nor swiping the tile away. So for example, for the sched user case, the tiles show the content of the url when it was discovered, but this is not updated and so the new events are not shown from one day to the next one.
It is necessary to close the app and open it again.

There should be a way so that we could get the tiles updated with the new content by refreshing the app. Maybe with the pull down to refresh action or any other way we find useful but something bettter than having to close the app :(

**Comment by wilsonpage** [comment]
I would not say this is the task of the client. In the case of the Sched tile, it is that tile's (mini-app's) task to ensure that the content is fresh. This tile should download the JSON for that current day and periodically check that the sessions displayed are still relevant. If time has elapsed till the next day, then the sched tile/mini-app should fetch JSON for that day and re-render.

To draw a comparison: When you visit facebook.com in your browser and you keep the tab open, you expect the content to remain fresh. You don't expect your brower to refresh facebook.com on their behalf.

+@arcturus to comment.

**Comment by arcturus** [comment]
I actually would say it is the magnet client it self.

We cannot trust on all pages doing what facebook does, or waiting for visibility changes. 

Also open the door to do a better refreshing. Yesterday when showing the demo and having a huge list of tiles, the list didn't 'show' any new update when refreshing cause we were keeping the tiles and adding at the bottom, leaving the user with the feeling nothing changed.

**Comment by wilsonpage** [comment]
#141 should be an acceptable fix.
