### ISSUE TITLE
Tiles in expanded view which are not shown totally fine

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#149]
Not sure about how these tiles should be shown, sharing them to check if there are an issue with them since these are urls we are going to broadcast.

This is the #mozlondon stream:
https://tengam.org/oembed/?url=https%3A%2F%2Fmozilla-magnet.github.io%2Ftwitter-search-embed%2F%3Fhashtag%3Dmozlondon%26widget-id%3D738359369146961920
And short: https://goo.gl/RajcrZ
It is cut at the end and not sure if this tile should grow.
![screenshot_2016-06-10-10-09-48](https://cloud.githubusercontent.com/assets/1897507/15958190/5777448c-2ef4-11e6-96db-6460bfe2e216.png)

And, this is the link for an example of an image for the sharing recent photos/videos use case:
https://tengam.org/oembed/?url=https%3A%2F%2Fc2.staticflickr.com%2F8%2F7673%2F27544979985_9648781cfe_h.jpg
And short: https://goo.gl/fuyy5f

In expanded view the tile grows more that the image height, so you can scroll down but there is no more image, just white screen.
![screenshot_2016-06-10-10-08-26](https://cloud.githubusercontent.com/assets/1897507/15958288/f2c9ed36-2ef4-11e6-9680-ef6612187dec.png)

**Comment by isabelrios** [comment]
Also @wilsonpage if I remember correctly when you showed us the maps tile, you could move it in expanded view, right? but I cannot :( (with latest nightly 73f35b8 on android)

**Comment by wilsonpage** [comment]
Sounds like there's three issues bundled into one here:
1. Twitter tile doesn't grow when expanded
2. Direct links to images look broken
3. Google maps tile is not responding to touch when expanded

I'll take a look when I get into the office.

**Comment by isabelrios** [comment]
Thanks! If you prefer I can open three separate issues, did not want to make too much noise before checking with you.
