### ISSUE TITLE
Unexpected screen: mixed expanded with normal view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#151]
Do not have the steps to reproduce yet, but have seen this twice today with 73f35b8 (nightly build)

Here an screenshot:
![screenshot_2016-06-16-15-01-44](https://cloud.githubusercontent.com/assets/1897507/15965312/5ce4cef2-2f1d-11e6-8be7-1fca5bc569ca.png)

There is the close button as in the expanded view, but two tiles are shown

**Comment by wilsonpage** [comment]
This is due to https://github.com/mozilla-magnet/magnet-client/issues/122

**Comment by wilsonpage** [comment]
Closing this to continue conversation there.

**Comment by isabelrios** [comment]
Okay, thanks!
