### ISSUE TITLE
Close button is not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#158]
Although if you tap on its place, the expanded view is closed.
Could it be something related with a change in its colour/background?
(seen with latest master  4f627c8, was not happening in eec33996)

**Comment by wilsonpage** [comment]
Unable to reproduce at my end.

**Comment by isabelrios** [comment]
I installed the app again and now is shown...weird. I also checked it is shown in the newest daily build 4f627c8.
Closing this issue, sorry about it
