### ISSUE TITLE
UX V2

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#161]
We should show 'X meters/feet away' on tiles to give a little more context. Maybe only on the 'expanded' view.

**Comment by wilsonpage** [comment]
<img src="https://cloud.githubusercontent.com/assets/1020551/16447904/aaf47c3c-3de6-11e6-84f1-3b74211180f9.png" width="320" height="620"/>

**Comment by lime124** [comment]
I like having the distance on the main tile to give a little more context as to where it's coming from. I like this new organization and it's like a good iteration. I'd also like to explore a radar type view - perhaps people could even choose between tile vs radar like choosing between date and week view in calendar.

**Comment by wilsonpage** [comment]
@lime124 as discussed on IRC I don't think the radar view will be technically possible :( As an alternative view I think I could be good to group tiles in a similar UI by site. The UI would look similar to above but each tile would represent a site (eg. 'Facebook', 'Twitter', 'Wikipedia'), sort of like a 'zoomed-out' version. Tapping a site tile would present the user with a list of URLs like above.

**Comment by samgiles** [comment]
You could have an airdrop style UI where concentric lines from "you" radiate outwards to display distance, and things are arranged in this space.

<img width="476" alt="screenshot 2016-06-29 13 20 22" src="https://cloud.githubusercontent.com/assets/840334/16451668/586f2fd2-3dfc-11e6-872c-46784df2e911.png">

I do like the grid ^^^

**Comment by wilsonpage** [comment]
I just noticed that with the grid layout we would not be able to have our swipe-to-dismiss interaction. This could be an issue if we want dismissing tiles to be super easy. I could try to sketch up an alternative layout where items span full-width.

**Comment by arcturus** [comment]
I have the feeling that we should not solve the distance problem with the grid layout.
Those are different problems, not saying we should not do grid layout, just that is a different thing.

I like the way physical web app does it, you do long press to get extra information. But that could be too much. What about adding it so far as part of the information that we put in the header?

By header I mean the info before the card, where we show the url, we could do something like:

http://myruls.es | 4 m. from you

**Comment by wilsonpage** [comment]
Agreed. This discussion is leaking out from the distance issue. I couldn't find a better issue to dump the sketch, so it landed here. Post London we found several issues with the UX, I think they should be addressed as a 'UX V2' and implemented as one.

**Comment by arcturus** [comment]
+1 to that!

**Comment by wilsonpage** [comment]
Adapted the above visual to work as a list so we can maintain the swipe-to-dismiss UX. Having a meeting tomorrow with Przemek to see if he can give us further advice.

<img width="320" src="https://cloud.githubusercontent.com/assets/1020551/16770610/7f488d62-4845-11e6-90d9-1417d8d99357.png"/>

**Comment by wilsonpage** [comment]
<img src="https://cloud.githubusercontent.com/assets/1020551/16923724/89b1c57a-4d13-11e6-81d9-bc493a013ed8.png" width="320"/>

<img src="https://cloud.githubusercontent.com/assets/1020551/16923746/ac84f2ac-4d13-11e6-92e2-938a9a72422a.png" width="320"/>

**Comment by wilsonpage** [comment]
<img src="https://cloud.githubusercontent.com/assets/1020551/16987176/ccaf84a0-4e82-11e6-86cb-397dee7dfcce.png" width=320 />

**Comment by lime124** [comment]
It's better but something still feels off that I can't put my figure on. I think the last one is better than the dotted ones. 

when normally measuring distance you have a start point and an end point - here that is implied but i'm not confident that it's apparent. what if we made those two point more obvious by using say a little person for you and a dot (or whatever) as the beacon. then you are showing that from you to the beacon is 1m.

maybe @KatieCaldwell will have some epiphanies while i sleep :)
