### ISSUE TITLE
Facebook tiles are not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#169]
Not sure if there is a problem on the app or I should configure something on Facebook or any other place, but if I set a beacon with a facebook id, it is not shown on magnet app but it appears on physical web.
In physical web it appears as Security Check Required, but tapping on it the facebook profile is open.
![physical](https://cloud.githubusercontent.com/assets/1897507/16310404/b148416e-396c-11e6-9b7b-c1df5dee877b.png)
![screenshot_2016-06-23-17-51-29](https://cloud.githubusercontent.com/assets/1897507/16310421/c4e8a0c4-396c-11e6-83ce-d6dcfba970b4.png)

On magnet nothing is shown.
The privacy setting is set to public so everyone can see it.

**Comment by isabelrios** [comment]
With the simplified MVP we can see a tile now, please see screenshot attached, and tapping on it takes us to the correct place. Just wondering if there is a way to change the fetching content tile to some default tile after some time trying to fetch the content. To show like a default tile for this situations in which for some reason the fetch does not work.
![img_0016](https://cloud.githubusercontent.com/assets/1897507/17325445/e828be08-58ab-11e6-9f9d-77cdfaff88f3.PNG)

It is not a critical issue, but maybe a nice to have...what do you think @wilsonpage?

**Comment by wilsonpage** [comment]
Can you clarify what URL you are advertising?

**Comment by isabelrios** [comment]
Sorry @wilsonpage I thought I had added that to the description:
This is the url:
https://www.facebook.com/isabel.riosescobar
And shorter:
https://goo.gl/8hXTJn

**Comment by wilsonpage** [comment]
This should be fixed now. Can you clarify and close if so.

NOTE: In the physical-web screenshot above you can see that their scraper was blocked from the content. I noticed this happening from Travis, meaning I had to disable our Facebook unit-tests. If we run into this we will either have to:
- A. Make requests from a pool of IP addresses
- B. Try to use official Facebook API

**Comment by isabelrios** [comment]
I can see the tile now! Closing this
