### ISSUE TITLE
Spinner icon shown when tiles are removed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#170]
If the available tiles are removed, the Nothing found screen is shown, the spinner icon is also on that screen. It is an static icon, it does not change as it it was waiting for something to happen.
![spinnernothingfound](https://cloud.githubusercontent.com/assets/1897507/16372625/d248bcde-3c4d-11e6-93a8-e9fbfb05b310.PNG)

After a while when the app starts scanning, the Nothing found string dissapears but the icon is still there
![spinnerscanning](https://cloud.githubusercontent.com/assets/1897507/16372721/8228c90a-3c4e-11e6-89fe-b5cf72036820.PNG)

**Comment by isabelrios** [comment]
If there are two tiles and the first one is removed, the second one is not moved to the first place as we see with android app. The place is there with the spinner icon: 
![tileremoved](https://cloud.githubusercontent.com/assets/1897507/16374672/d22ecd38-3c57-11e6-85c1-af532c1726a8.png)

**Comment by wilsonpage** [comment]
I managed to recreate this. Will look into it when we decide to pref this feature back on :)

**Comment by wilsonpage** [comment]
I have a feeling it might be something to do with us adjusting the scroll position after the tile has been removed.

**Comment by isabelrios** [comment]
Closing this issue since this feature is off. Will open again if it is turned on and still happens
