### ISSUE TITLE
Notifications - "1 items near you" would be better "1 item near you"

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#178]
When there is only one beacon around the notification says "1 items near you" it is just the items word which is in plural.
Not a critial issue but nice to change if possible :)

**Comment by wilsonpage** [comment]
I think this is nice wording that avoids the inaccurate numbering issue.

![](https://cdn-images-1.medium.com/max/1600/1*nWEB6VTJC4RCdebKbEFupQ.png)

Perhaps a variation on this:

> Magnet found websites nearby
> Tap to explore

**Comment by isabelrios** [comment]
Yeah, that could be a good option :)

**Comment by arcturus** [comment]
@isabelrios I've just landed new notifications in ios. We got ride of the badge and we use a notification saying there ware web pages around you.

**Comment by isabelrios** [comment]
@wilsonpage, @arcturus is it planned to change also the android notification to show that general notification instead of the number of items found for the Simplified MVP or for future versions?

**Comment by wilsonpage** [comment]
Yes, this is a very easy change to make.

**Comment by wilsonpage** [comment]
I've included this change as part of MVP branch. The wording is now: 

"Content found nearby - Tap to explore"

**Comment by isabelrios** [comment]
We can close this issue now since the wording is different and this issue does not apply with the current implementation.
