### ISSUE TITLE
'An app wants to turn on Bluetooth' warning is not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#179]
Looks like this is a regression, opening the app directly does not show the message.

There is also this scenario, initially bluetooth is on, we see a magnet notification, then bluetooth is disabled and if we tap on the notification to open the app, there is no warning letting us know that we have to enable bluetooth. The app shows 'Scanning' and then 'Nothing found'

**Comment by wilsonpage** [comment]
Ah damn, this code got accidentally removed [here](https://github.com/mozilla-magnet/magnet-client/pull/176/commits/57c5f0db49de4cfecc8adceb11ebbb3b589a6754) when we moved to use magnet-scanner-android.

**Comment by wilsonpage** [comment]
Closed by 887b081
