### ISSUE TITLE
Notifications - Opening app from a notification should open it in list view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#189]
As commented by email..
It could happen that you open a tile in expanded view. Then leave the app in background. The notification appears on the screen and tapping on it takes you to the app to the expanded tile, not to the list view.

**Comment by oteo** [comment]
@isabelrios once we removed the expanded feature in the client, wouldn't this issue be removed?

**Comment by isabelrios** [comment]
Yes, we can close this if we are not going to have the expanded view anymore.

**Comment by isabelrios** [comment]
Once we have again the POI expanded view, this issue is happening.
Steps:
Fake the position to a place with several POIs
Wait to receive the notifications
Tap on one of the notifications and open the POI expanded view
Go back to utility tray and tap on other notification about a different POI

Expected:
The app is open showing that specific POI or the general list view to see all POI

Actual:
The app is open in the first expanded POI.

**Comment by isabelrios** [comment]
There is something similar when you left the app in background in the subscriptions view. 
When you have a notification and tap on it to open the app, it is not open on the POI the notification is about or in the main list view, the app is open in the subscriptions view

**Comment by isabelrios** [comment]
This will be solved at least for android once issue #331 lands

**Comment by oteo** [comment]
The issue in Android is solved, after landing #331 but the issue is still happening in iOS

**Comment by oteo** [comment]
The issue continue happening in iOS after landing PR #355 but I am going to open a new one to report it
