### ISSUE TITLE
Urls appear cut in the metrics reports

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#190]
There are few examples of urls that are cut so we do not know (although we can guess) which urls are. You can see that here:
https://sql.telemetry.mozilla.org/queries/552#table

First url is:
https://tengam.org/oembed/?height=600 
(We know this corresponds to the twitter url)

Second one is:
https://tengam.org/oembed/?width=400 
(Our guessing this is the London Map url)

And there are a few more.

We would need to understand why the urls do not appear completely and where we can fix it so that in next reports there are no doubts about the urls shown.

**Comment by wilsonpage** [comment]
INVALID
