### ISSUE TITLE
Add a way to dismiss tiles

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#2]
When content is not relevant there should be a way for users to dismiss tiles, this decision should likely be persisted with the option to revoke if need be.

A swipe-away gesture might be nice. Although I'm concerned this might be tricky if swipe gesture conflicts with content inside a WebView tile. For example, if a tile has a horizontal range-slider component, how do we make sure the tile isn't mistakenly panned away during interaction?

This also raises the question of how touch events work inside a WebView inside a ScrollView. How do we prevent the ScrollView scrolling when the user is interacting with a touch based control?

Perhaps @etiennesegonzac knows more? :)

**Comment by wilsonpage** [comment]
Let's wait for UX input before implementing anything here :)

**Comment by samgiles** [comment]
We already have a context menu (which pops up when I'm refreshing sometimes) - maybe something like: https://github.com/dancormier/react-native-swipeout would be nice?
