### ISSUE TITLE
Analytics all the things

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#204]
We should tie our app analytics into the the official Android and iOS SDKs to give us the richest metrics possible.
- [x] App install
- [x] App launch
- [x] List refresh
- [x] Navigate to item
- [x] Items found (not sure exactly when/how to record this)
- [x] Settings view opened
- [ ] Taps on settings list item items
- [x] App to background
- [x] App to foreground
- [ ] Opening the app from a notification (android)
- [ ] Opening the app from a notification (ios)
- [ ] Dismissing a notification (android)
- [ ] Dismissing a notification (ios)
- [ ] App killed from task manager (android)
- [ ] App killed from task manager (ios)

---

Please edit above list if you have other requirements

**Comment by wilsonpage** [comment]
- Opening the app from a notification
- Dismissing a notification

**Comment by isabelrios** [comment]
Not sure if we can have these:
- App closed
- App uninstalled
