### ISSUE TITLE
Tiles are continuously grayed out and back to normal color when 'Remove old items' is on

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#229]
Please see the issue here:
https://youtu.be/FhcC9SNMZbg

The enviroment did not change while the video was recorded, there was one beacon always turned on.

**Comment by wilsonpage** [comment]
This suggests that either we're not receiving broadcasts regularly enough or there's some dodgy logic in the way we expire tiles.

How far away was the beacon from the device?

**Comment by isabelrios** [comment]
It was on my desk, close to the device, less than 1m

**Comment by isabelrios** [comment]
This is not reproducible in ios with latest version b77a61e. Open another issue for android #307 and a different behaviour in ios for virtual beacons
