### ISSUE TITLE
Event action 'app-launch-from-notification' is not recorded for iOS

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#244]
This is happening in both dev and market version. The information about launching the app from the notification is not being recorded.

**Comment by isabelrios** [comment]
I am afraid this issue has to be re-opened. I am still not able to see the app-launch-from-notification event in GA coming from iOS devices.

**Comment by oteo** [comment]
It seems that after landing Sam's patch "Add ability to call Google Analytics from native code " (Issue #296 ) this issue will become obsolete. Let's move it to the next sprint just to confirm it will work fine.

**Comment by isabelrios** [comment]
According to latest comment and after latest checks, this issue is closed and it will be followed in issue #362
