### ISSUE TITLE
Errors when compiling magnet for iOS10

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#245]
I tried to compile the build for my ipod (10.0.1) with both xCode7 and xCode8 and could not compile the build. 
I got different errors in each one, will copy them here. I will try also after updating my mac from El Capitan to Sierra. 
Opening the issue in the meantime.

**Comment by isabelrios** [comment]
This has been solved. Compiled on xCode 8 and iOS 10 successfuly.
I got two warnings though:
/~/magnet-client/ios/MagnetScannerReact.swift:26:8: 'sendDeviceEventWithName(_:body:)' is deprecated: Subclass RCTEventEmitter instead

/~/magnet-client/ios/Magnet/AppDelegate.m:59:34: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead

**Comment by arcturus** [comment]
Closed by #248
