### ISSUE TITLE
Update description in stores

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-client#251]
Right now the description in the stores for both android and ios includes the experiment in View Source.

Now that's totally out of date, we will need to remove the references to view source and keep a more app specific description.

**Comment by arcturus** [comment]
@wilsonpage @oteo what do you think?

**Comment by wilsonpage** [comment]
Ship it.

**Comment by arcturus** [comment]
Ship what :), right now we have this:

> Are you ready to explore the Physical Web around you?
> 
> With the Project Magnet app for Android, you can experience a web that’s attached to physical objects. A web that you can discover, while you walk!
> 
> Project Magnet lets you engage physical web-based content in a fun and safe way, by respecting your privacy, since your identity isn’t passed by us to any beacons.
> 
> For those attending View Source Berlin, you will be able to get real-time information from the things around you in the form of tiles in the app’s main feed, thanks to strategically placed beacons throughout the event.
> 
> You’re notified of content near you via push notifications, and you can easily collect tiles along your journey.
> 
> For those that can’t find any physical web content where you live, keep the app installed and up-to-date for a chance to participate if an event is near you in the future.
> 
> We look forward to helping you walk the web.

**Comment by wilsonpage** [comment]
> Are you ready to explore the Physical Web around you?
> 
> With the Project Magnet app for Android, you can experience a web that’s attached to physical objects. A web that you can discover, while you walk!
> 
> Project Magnet lets you engage physical web-based content in a fun and safe way, by respecting your privacy, since your identity isn’t passed by us to any beacons.
> 
> You’re notified of content near you via push notifications, and you can easily collect tiles along your journey.
> 
> We look forward to helping you walk the web.

**Comment by oteo** [comment]
@arcturus is the content provided by @wilsonpage enough? or do you want to provide info about virtual beacons?

**Comment by dbialer** [comment]
Link to doc here with new descriptions.
https://docs.google.com/document/d/1DVRpf7TaY5LxFKVloJ3HDA4_Nx-Jltje6Q7hvrKHO1s/edit?usp=sharing

**Comment by dbialer** [comment]
Need new screenshots.

**Comment by oteo** [comment]
Folder with the images (4 for android and 4 for iOS): 
https://drive.google.com/open?id=0B01m7pXAhdJmT0drWW9xSG1QcVk
They are also included in the doc with the description

**Comment by arcturus** [comment]
@oteo unfortunately for ios we need screenshots that include the phone, there are several services that get you images for the app store from your screenshots like:
https://launchkit.io/screenshots/
http://www.appshots.io/app-screenshot-guide

**Comment by oteo** [comment]
@arcturus done, have a look at it and let me know if it's fine now

**Comment by oteo** [comment]
Note: I have just included also the 5.5 inch images for iOS in the folder as it was requested by Apple when Francisco uploaded the client last night.

Resolving the issue
