### ISSUE TITLE
Notifications - iOS10 issues with notifications

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#252]
- Notifications are not aggregated
  ![img_0021](https://cloud.githubusercontent.com/assets/1897507/19389163/18c5a458-9223-11e6-8f00-ede5d34da703.PNG)
- Do not know STR yet, but it is possible to see more than one magnet notification on the lockscreen

**Comment by isabelrios** [comment]
Screenshot for the second example:
![img_0023](https://cloud.githubusercontent.com/assets/1897507/19427572/2452f68a-9445-11e6-8364-eafe9d89b01d.PNG)

And how I saw it. The device was not use for the a long time(one night), then I started to broadcast from magnet desktop different urls, a notification appeared on the lockscreen for each one (did not unblock the device to open the app while changing the url broadcasted)

**Comment by wilsonpage** [comment]
I think this is due to the way that iOS10 changed the way notifications are managed.

**Comment by wilsonpage** [comment]
@arcturus may know more.

**Comment by isabelrios** [comment]
This is not reproducible in latest master 99311eb
