### ISSUE TITLE
Regression - Metrics for dev iOS build are recorded under prod client

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#253]
Although the app is built with xCode the metrics collected appear under the production client not the dev one.

**Comment by wilsonpage** [comment]
I have a feeling that we may have accidentily flipped the 'Release' switch. We need to make sure it's still in 'Debug' mode.

**Comment by arcturus** [comment]
With latest commit by @wilsonpage this should have been solved.

@isabelrios could you check?

**Comment by isabelrios** [comment]
@arcturus @wilsonpage Yes, this is fixed now! iOS metrics appear under dev client. Thanks!
