### ISSUE TITLE
When I have a spare moment and I’m curious, I want to be informed about Points of Interest around me, so I can decide whether to investigate further.

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#260]
I have created a specific US for this sprint (Sprint 6) to ensure that we are able to discover Physical and Virtual beacons.
I have not specified the distance, as we commented above for Virtual beacons will depend on the real testing and also for physical web beacons will also depend on the range of the beacons.

**Comment by wilsonpage** [comment]
What feature is this referring to? Passive notifications or active searching?

**Comment by oteo** [comment]
@wilsonpage active searching

**Comment by wilsonpage** [comment]
@oteo what is missing from this story? Don't we already have this conceptually?

**Comment by oteo** [comment]
@wilsonpage we are already testing it for android, and we have not started the testing for iOS, let us test it first and open the possible issues and we will close it after that ;)
