### ISSUE TITLE
Without changing our location, Virtual beacons tiles disappear when we refresh Magnet app

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#267]
This issue has been detected during remote testing, and using fake GPS app. We would need @samgiles @wilsonpage or @arcturus to check if it still happens in real environment.

Steps:
1. Go to a location with virtual beacons around.
2. Open Magnet and check the tile with the Virtual Beacon info is shown in Magnet
3. Refresh Magnet app (scroll down main Magnet screen) without changing your location

**Result**: Tile disappears
**Expected:** Tile should still be there as we have not changed the location

**Comment by arcturus** [comment]
mmm that's pretty weird, we will need to check which call are we actually doing to the content server.

**Comment by wilsonpage** [comment]
I can reproduce this. Looking into it.

**Comment by oteo** [comment]
Verified that the issue has been fixed with latest android and ios version
