### ISSUE TITLE
Crash when launching the nightly build

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#269]
The app is installed correctly but when opening it, it is stopped. These are the logs:

D/StatusBar.NetworkController( 1387): hasService: mServiceState=1 1 voice home data home null null null null null null  Unknown Unknown CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1 EmergOnly=true retVal=false
D/StatusBar.NetworkController( 1387): refreshViews: Data not connected!! Set no data type icon / Roaming
D/StatusBar.NetworkController( 1387): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f0203bf/com.android.systemui:drawable/stat_sys_wifi_signal_3_fully combinedActivityIconId=0x7f0203b6 mobileLabel=Emergency calls only wifiLabel="Orange-6421"xxxxXXXXxxxxXXXX emergencyOnly=true combinedLabel="Orange-6421"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mQSPhoneSignalIconId=0x7f0200bd/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mDataTypeIconId=0x0/(null) mQSDataTypeIconId=0x0/(null) mNoSimIconId=0x7f0201dc/com.android.systemui:drawable/stat_sys_no_sim mVolteIconVisible=false mWifiIconId=0x7f0203bf/com.android.systemui:drawable/stat_sys_wifi_signal_3_fully mQSWifiIconId=0x7f0200d2/com.android.systemui:drawable/ic_qs_wifi_full_3 mWifiActivityIconId=0x7f0203b6/com.android.systemui:drawable/stat_sys_wifi_inout mBluetoothTetherIconId=0x1080775/android:drawable/stat_sys_tether_bluetooth
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): changing data overlay icon id to 2130838454
D/StatusBar.NetworkController( 1387): hasService: mServiceState=1 1 voice home data home null null null null null null  Unknown Unknown CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1 EmergOnly=true retVal=false
D/StatusBar.NetworkController( 1387): refreshViews: Data not connected!! Set no data type icon / Roaming
D/StatusBar.NetworkController( 1387): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f0203c1/com.android.systemui:drawable/stat_sys_wifi_signal_4_fully combinedActivityIconId=0x7f0203b6 mobileLabel=Emergency calls only wifiLabel="Orange-6421"xxxxXXXXxxxxXXXX emergencyOnly=true combinedLabel="Orange-6421"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mQSPhoneSignalIconId=0x7f0200bd/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mDataTypeIconId=0x0/(null) mQSDataTypeIconId=0x0/(null) mNoSimIconId=0x7f0201dc/com.android.systemui:drawable/stat_sys_no_sim mVolteIconVisible=false mWifiIconId=0x7f0203c1/com.android.systemui:drawable/stat_sys_wifi_signal_4_fully mQSWifiIconId=0x7f0200d3/com.android.systemui:drawable/ic_qs_wifi_full_4 mWifiActivityIconId=0x7f0203b6/com.android.systemui:drawable/stat_sys_wifi_inout mBluetoothTetherIconId=0x1080775/android:drawable/stat_sys_tether_bluetooth
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
I/Timeline( 1965): Timeline: Activity_launch_request id:org.mozilla.magnet time:1717587
I/ActivityManager(  861): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.mozilla.magnet/.MainActivity bnds=[360,752][528,952]} from uid 10110 on display 0
V/WindowManager(  861): addAppToken: AppWindowToken{16866326 token=Token{36f6a681 ActivityRecord{17d8c268 u0 org.mozilla.magnet/.MainActivity t3068}}} to stack=1 task=3068 at 0
V/WindowManager(  861): Adding window Window{a50a4b9 u0 Starting org.mozilla.magnet} at 5 of 10 (after Window{19efa674 u0 com.android.settings/com.android.settings.SubSettings})
D/audio_hw_primary(  324): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
D/audio_hw_primary(  324): start_output_stream: enter: stream(0xb54a5280)usecase(1: low-latency-playback) devices(0x2)
D/audio_hw_primary(  324): select_devices: out_snd_device(47: speaker) in_snd_device(0: )
D/hardware_info(  324): hw_info_append_hw_type : device_name = speaker
D/ACDB-LOADER(  324): ACDB -> send_audio_cal, acdb_id = 15, path =  0
D/ACDB-LOADER(  324): ACDB -> send_adm_topology
D/ACDB-LOADER(  324): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  324): ACDB -> send_asm_topology
D/ACDB-LOADER(  324): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
D/ACDB-LOADER(  324): ACDB -> send_audtable
D/ACDB-LOADER(  324): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(  324): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  324): ACDB -> send_audvoltable
D/ACDB-LOADER(  324): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/ACDB-LOADER(  324): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  324): ACDB -> send_afe_cal
D/ACDB-LOADER(  324): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/ACDB-LOADER(  324): ACDB -> AUDIO_SET_AFE_CAL
D/audio_hw_extn(  324): audio_extn_get_anc_enabled: anc_enabled:0
D/audio_hw_primary(  324): select_devices: done
I/ActivityManager(  861): Start proc 14450:org.mozilla.magnet/u0a675 for activity org.mozilla.magnet/.MainActivity
V/ActivityManager(  861): Display changed displayId=0
W/ResourceType(14450): Found multiple library tables, ignoring...
V/fb-UnpackingSoSource(14450): locked dso store /data/data/org.mozilla.magnet/lib-main
I/fb-UnpackingSoSource(14450): dso store is up-to-date: /data/data/org.mozilla.magnet/lib-main
V/fb-UnpackingSoSource(14450): releasing dso store lock for /data/data/org.mozilla.magnet/lib-main
I/art     (14450): Thread[1,tid=14450,WaitingForJniOnLoad,Thread*=0xb4827800,peer=0x74d1f000,"main"] recursive attempt to load library "/data/app/org.mozilla.magnet-1/lib/arm/libfb.so"
D/org.mozilla.magnet.MainActivity(14450): alarm set
D/org.mozilla.magnet.MainActivity(14450): on resume
D/org.mozilla.magnet.MainActivity(14450): set active: true
D/MagnetWebViewManager(14450): new
D/OpenGLRenderer(14450): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   (14450): Validating map...
V/WindowManager(  861): Adding window Window{22c3e1d6 u0 org.mozilla.magnet/org.mozilla.magnet.MainActivity} at 5 of 11 (before Window{a50a4b9 u0 Starting org.mozilla.magnet})
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
I/Adreno-EGL(14450): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030_msm8974_LA.BF.1.1.1_RB1__release_AU ()
I/Adreno-EGL(14450): OpenGL ES Shader Compiler Version: E031.25.03.06
I/Adreno-EGL(14450): Build Date: 07/13/15 Mon
I/Adreno-EGL(14450): Local Branch: mybranch11906725
I/Adreno-EGL(14450): Remote Branch: quic/LA.BF.1.1.1_rb1.26
I/Adreno-EGL(14450): Local Patches: NONE
I/Adreno-EGL(14450): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030 + 6151be1 + a1e0343 + 002d7d6 + 7d0e3f7 +  NOTHING
I/OpenGLRenderer(14450): Initialized EGL, version 1.4
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
D/OpenGLRenderer(14450): Enabling debug mode 0
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
I/Timeline(14450): Timeline: Activity_idle id: android.os.BinderProxy@389c21d3 time:1717848
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
I/ActivityManager(  861): Displayed org.mozilla.magnet/.MainActivity: +233ms
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
W/unknown:ViewManagerPropertyUpdater(14450): Could not find generated setter for class org.mozilla.magnet.webview.MagnetWebViewManager
E/Vold    (  270): Failed to find mounted volume for /storage/sdcard1/Android/data/org.mozilla.magnet/cache/
W/Vold    (  270): Returning OperationFailed - no handler for errno 0
W/ContextImpl(14450): Failed to ensure directory: /storage/sdcard1/Android/data/org.mozilla.magnet/cache
D/NsdService(  861): New client listening to asynchronous messages
D/NsdService(  861): New client, channel: com.android.internal.util.AsyncChannel@1a4d7fb0 messenger: android.os.Messenger@2072e29
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$5>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$5>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$10>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$10>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$2>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$2>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$9>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$9>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$8>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$8>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$7>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$7>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$1>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$1>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$6>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$6>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$4>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$4>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$3>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$3>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$1>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$1>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$2>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$2>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$3>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$3>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzq$1>
I/art     (14450): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzq$1>
E/AndroidRuntime(14450): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(14450): Process: org.mozilla.magnet, PID: 14450
E/AndroidRuntime(14450): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(14450):    at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(14450):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(14450):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(14450):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(14450):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(14450):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(14450):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(14450): Caused by: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzf, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
E/AndroidRuntime(14450):    at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
E/AndroidRuntime(14450):    at com.google.android.gms.common.api.GoogleApiClient$Builder.zzarg(Unknown Source)
E/AndroidRuntime(14450):    at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
E/AndroidRuntime(14450):    at org.mozilla.magnet.scanner.geolocation.ScannerGeolocation.<init>(ScannerGeolocation.java:52)
E/AndroidRuntime(14450):    at org.mozilla.magnet.scanner.MagnetScanner.useGeolocation(MagnetScanner.java:70)
E/AndroidRuntime(14450):    at org.mozilla.magnet.MagnetScannerReact.<init>(MagnetScannerReact.java:28)
E/AndroidRuntime(14450):    at org.mozilla.magnet.MyAppPackage.createNativeModules(MyAppPackage.java:20)
E/AndroidRuntime(14450):    at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:944)
E/AndroidRuntime(14450):    at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:865)
E/AndroidRuntime(14450):    at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:108)
E/AndroidRuntime(14450):    at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:209)
E/AndroidRuntime(14450):    at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:188)
E/AndroidRuntime(14450):    at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(14450):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(14450):    ... 3 more
D/ActivityManager(  861): New dropbox entry: org.mozilla.magnet, data_app_crash, 4b748e6b-3efd-476f-8451-0f8340aa38a9
W/ActivityManager(  861):   Force finishing activity 1 org.mozilla.magnet/.MainActivity
D/org.mozilla.magnet.MainActivity(14450): on pause
D/org.mozilla.magnet.MainActivity(14450): set active: false
W/ContextImpl(13151): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1761 android.content.ContextWrapper.bindService:539 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192
I/OpenGLRenderer(  861): Initialized EGL, version 1.4
I/Timeline( 1965): Timeline: Activity_idle id: android.os.BinderProxy@38a8cbb6 time:1718098
I/Timeline(  861): Timeline: Activity_windows_visible id: ActivityRecord{3e69f8d6 u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t3058} time:1718333
D/StatusBar.NetworkController( 1387): hasService: mServiceState=1 1 voice home data home null null null null null null  Unknown Unknown CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1 EmergOnly=true retVal=false
D/StatusBar.NetworkController( 1387): refreshViews: Data not connected!! Set no data type icon / Roaming
D/StatusBar.NetworkController( 1387): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f0203c1/com.android.systemui:drawable/stat_sys_wifi_signal_4_fully combinedActivityIconId=0x7f0203b5 mobileLabel=Emergency calls only wifiLabel="Orange-6421"xxxxXXXXxxxxXXXX emergencyOnly=true combinedLabel="Orange-6421"xxxxXXXXxxxxXXXX mAirplaneMode=false mDataActivity=0 mPhoneSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mQSPhoneSignalIconId=0x7f0200bd/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0203a0/com.android.systemui:drawable/stat_sys_signal_null mDataTypeIconId=0x0/(null) mQSDataTypeIconId=0x0/(null) mNoSimIconId=0x7f0201dc/com.android.systemui:drawable/stat_sys_no_sim mVolteIconVisible=false mWifiIconId=0x7f0203c1/com.android.systemui:drawable/stat_sys_wifi_signal_4_fully mQSWifiIconId=0x7f0200d3/com.android.systemui:drawable/ic_qs_wifi_full_4 mWifiActivityIconId=0x7f0203b5/com.android.systemui:drawable/stat_sys_wifi_in mBluetoothTetherIconId=0x1080775/android:drawable/stat_sys_tether_bluetooth
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): refreshSignalCluster - setMobileDataIndicators:  mHasMobileDataFeature = true mPhoneSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mDataSignalIconId = com.android.systemui:drawable/stat_sys_signal_null mMobileActivityIconId = (null) mDataTypeIconId = (null) mNoSimIconId = com.android.systemui:drawable/stat_sys_no_sim
D/StatusBar.NetworkController( 1387): changing data overlay icon id to 2130838453
I/ActivityManager(  861): Killing 12752:com.sonymobile.social.services/u0a36 (adj 15): empty #26
W/lights-worker(  277): _schedule_work: 'bl_update' already scheduled
W/lights-worker(  277): _schedule_work: 'bl_update' already scheduled
W/ResourceType( 1387): Found multiple library tables, ignoring...
W/ResourceType( 1387): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1387): Failure retrieving resources for org.mozilla.magnet: Resource ID #0x0
W/lights-worker(  277): _schedule_work: 'bl_update' already scheduled
D/Ulp_jni (  861): Location CB invoked
W/lights-worker(  277): _schedule_work: 'bl_update' already scheduled

**Comment by wilsonpage** [comment]
I think the critical line here is:

```
Caused by: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzf, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
```

**Comment by wilsonpage** [comment]
I have built a production release on my local machine, but I can't recreate the crash. This suggests there is some critical difference between my machine and the Travis machine that builds our nightlies.

I'll need help from @samgiles to debug this further.

**Comment by wilsonpage** [comment]
[This in the line](https://github.com/mozilla-magnet/magnet-scanner-android/blob/master/src/main/java/org/mozilla/magnet/scanner/geolocation/ScannerGeolocation.java#L52) (I think) it's crashing on.

**Comment by wilsonpage** [comment]
Moving to https://github.com/mozilla-magnet/magnet-scanner-android/issues/13
