### ISSUE TITLE
Not shown image in the tile for atlasobscure source

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#274]
I am not able to see the picture in atlasobscure tile for iOS.
The strange thing is that the picture is shown correctly for the tile in android
@arcturus can you have a look at it?

e.g. http://www.atlasobscura.com/places/the-churchill-war-rooms

**Tile in iOS**
![ios_atlasobscure](https://cloud.githubusercontent.com/assets/1402627/19762720/5489f062-9c3b-11e6-9e94-7141feeb82ae.PNG)
**Tile in Android**
![android_atlasobscure](https://cloud.githubusercontent.com/assets/1402627/19762724/56a50198-9c3b-11e6-87fb-92bd325e9b5c.png)

**Comment by wilsonpage** [comment]
This looks like a network error of some kind.

**Comment by wilsonpage** [comment]
I can reproduce. This is an example image that doesn't load:

http://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL2VkYjZkMjYwYmVjMjk2NDUzZF9JTUdfMDQ1OS5KUEciXSxbInAiLCJjb252ZXJ0IiwiLXF1YWxpdHkgOTEgLWF1dG8tb3JpZW50Il0sWyJwIiwidGh1bWIiLCI2MDB4PiJdXQ

**Comment by wilsonpage** [comment]
> "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

**Comment by wilsonpage** [comment]
Here's some info on how you can enable arbitrary loads of non-secure resources (eg. images). Apparently Apple strongly opposes this decision and it can risk your app failing review. http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

**Comment by wilsonpage** [comment]
I can confirm the above fix works.

**Comment by oteo** [comment]
Thanks @wilsonpage
