### ISSUE TITLE
Add ability to call Google Analytics from native code

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#296]
As notifications become more advanced more of our code has to run on the native side. We need to be able to call Google Analytics from native code so that we can learn from user interactions with notifications when the app is closed.

**Comment by wilsonpage** [comment]
We can either run this a parallel with `react-native-google-analytics-bridge` or replace it with our own wrapper that can be called from JS or Native code.

**Comment by arcturus** [comment]
Do you thikn it makes sense to send a PR to `react-native-google-analytics-bridge` to allow native use of the api?

**Comment by wilsonpage** [comment]
That would be cool.

**Comment by samgiles** [comment]
Gonna break this down into three tasks
- [x] Expose user preferences to native code through the `Api` mechanism.
- [ ] Expose the native GA libraries from the `react-native-google-analytics-bridge`
- [ ] Add calls to analytics from notifications and background tasks.

**Comment by wilsonpage** [comment]
@samgiles ... like a boss 😎

**Comment by samgiles** [comment]
Closed in #349
