### ISSUE TITLE
Magnet app for iOS freezes when subscribing/unsubscribing channels

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#306]
Magnet app for iOS freezes when subscribing/unsubscribing channels. You need to kill the app or stop the simulator and run the app again to make it work again.

Steps:
1. Launch Magnet application in iOS
2. Enter in the Subscriptions menu and subscribe/unsubscribe the channels (It's easy to reproduce, just need to do it 20-25 times)

SAw this error in the traces from the Xcode:

[Issue_subscriptions.txt](https://github.com/mozilla-magnet/magnet-client/files/571922/Issue_subscriptions.txt)

fatal error: 'try!' expression unexpectedly raised an error: database is locked: file /Library/Caches/com.apple.xbs/Sources/swiftlang_swift_2_2/swiftlang_swift_2_2-800.10.12/src/swift/stdlib/public/core/ErrorType.swift, line 54
2016-11-04 16:17:31.875164 Magnet[468:94356] fatal error: 'try!' expression unexpectedly raised an error: database is locked: file /Library/Caches/com.apple.xbs/Sources/swiftlang_swift_2_2/swiftlang_swift_2_2-800.10.12/src/swift/stdlib/public/core/ErrorType.swift, line 54
(lldb)

**Comment by arcturus** [comment]
wow, nice catch :)
