### ISSUE TITLE
Prompt to upgrade google-play-services when out of date

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#321]
If the device has a version of google-play-services that is less than the one we depend on, we must prompt them to upgrade.

**Comment by oteo** [comment]
@arcturus @wilsonpage do you think this bug need to be fixed to upload the client to the stores?

**Comment by arcturus** [comment]
We are not running in the very last version of google play, so hopefully we can delay it.

What do you think @wilsonpage ?

**Comment by wilsonpage** [comment]
This is fixed.
