### ISSUE TITLE
POI expanded view not shown completely

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#325]
I am not sure if we are going to be able to scroll in a POI expanded view, but so far that is not the case. Here you have an example in which it is not possible to see the full content and the button to visit its web site is not shown either.
@gmarty @wilsonpage 

![screenshot_2016-11-08-16-36-14](https://cloud.githubusercontent.com/assets/1897507/20105484/063ca3c8-a5d2-11e6-8d99-e59a2c70b29a.png)

**Comment by wilsonpage** [comment]
Nice catch @isabelrios. @gmarty can we make the POI view scrollable? We'll need to add a `<ScrollView>` to nest the content inside.
