### ISSUE TITLE
Exception when 'preferences' are `null`

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#330]
My client is throwing:

```
TypeError: Cannot convert undefined or null to object
```

On this line:
https://github.com/mozilla-magnet/magnet-client/blob/b77a61e/lib/app.js#L196

+@samgiles

**Comment by wilsonpage** [comment]
I guess this is because my db/datastore hasn't been initialized yet. IIUC we just have to cope with the `null` case.

**Comment by samgiles** [comment]
It would be better to not return null if we've created the route.  We return a promise so should just resolve later if we're waiting for something to be created.

**Comment by wilsonpage** [comment]
@samgiles not sure how it works, but I think in this case we're calling `.get()` before we've populated anything with `.post()`, thus `null`.

**Comment by wilsonpage** [comment]
IIRC empty JSON objects resolve to `null` in Android, not sure about IOS.

**Comment by arcturus** [comment]
> IIRC empty JSON objects resolve to null in Android, not sure about IOS.

Empy json objects in iOS don't resolve to nil.
