### ISSUE TITLE
[ios] Stop magnet scanner after some time when we do a scanning based on region change

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-client#345]
Right now we are not stopping the magnet scanner when it has been initialized from a region change.

We should stop it after certain time.

It's a follow up from #341

**Comment by wilsonpage** [comment]
Maybe this should cover the ios hack we have on the front end of never stopping the scanner either. This stuff should really be wrapped up inside the `magnet-scanner-ios`. It's an implementation detail that scanning should no be stopped if we need it to scan when the app is closed. Ideally the client would still call stop and start as normal and not have to be aware of these details.
