### ISSUE TITLE
Crash - Refresh the app when bluetooth is disabled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#363]
**Scenario**
There are physical and virtual beacons

**Steps**
Close the app
Disable bt
Open the app
Once the Bluetooth prompt appears, tap on Deny
Once the tiles are loaded, refresh once or more times

**Actual**
The debug app shows a red screen after refreshing several times
The nightly build crashes with the Project Magnet app stopped just refreshing once.

Please see video: 
https://youtu.be/ylkYmeci-fA

**Comment by oteo** [comment]
![screenshot_2016-11-24-06-42-47](https://cloud.githubusercontent.com/assets/1402627/20602316/03ad40bc-b25d-11e6-9316-7c352cf72dac.png)

**Comment by arcturus** [comment]
This has been fixed by #370
