### ISSUE TITLE
Crash - Tapping on visit web site in a POI that has not been loaded yet

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#365]
**Scenario**
There is a tile that is still fetching content

**Steps**
Tap on the tile
Once the POI view is open, tap on Visit website

**Actual**
The app crashes
https://youtu.be/LKlViSSvK-E

This is the error shown:
![screenshot_2016-11-24-13-28-17](https://cloud.githubusercontent.com/assets/1897507/20598636/3e067354-b24a-11e6-9b84-1eaf7d6d75ad.png)

**Comment by wilsonpage** [comment]
@isabelrios does that gimb.us tile ever load, or is it a broken link? I'm interested as items that are still 'fetching' should show the spinner in ItemScene until the request gets a response.
