### ISSUE TITLE
Telemetry - Telemetry setting needs to be turned off and on to start collecting data

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#379]
Something is not going on well with telemetry. It seems that now it is necessary to disable and enable telemetry setting and close and open the app to have the data recorded in GA. 
I do not remember having to do that in order to get the data recorded in the past.

Tested with:
Dev builds, nightly and the released build.

**Comment by oteo** [comment]
@samgiles or @wilsonpage can you have a look at it, please?
