### ISSUE TITLE
Crash when visiting a not real/valid URL from the POI view

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#384]
STR:
Pre-requisite: broadcast a non valid URL via physical web or Magnet Desktop app (e.g http://www.ffff.es)
1. Open Magnet app and check the tile in the main screen
2. Tap the tile with the non valid URL
3. POI view is shown with no content and click on "Visit Website" button
4. Error Red screen
![screenshot_android](https://cloud.githubusercontent.com/assets/1402627/20637023/edec62c6-b379-11e6-89c0-eb7b1af79f74.png)

**Comment by isabelrios** [comment]
This is the same error seen when the link was busted #365 and never loaded,

**Comment by isabelrios** [comment]
@oteo Can you still see this with latest build? I tried to reproduce but I cannot so far.

**Comment by oteo** [comment]
you are right @isabelrios , when I opened the bug I was testing Sam's branches because of the Telemetry issue so patch in #365 has not been landed yet. Now I am testing is master and the issue is resolved. Thanks a lot!
