### ISSUE TITLE
Support embeds of variable height

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#48]
Not all embeds have a fixed height. For example I may want to show a list of upcoming buses, if there is only one bus upcoming, I don't want to render a widget tall enough to accommodate three buses. Essentially the content length is variable.

So acheive this we'll need to inject some JS into the webview that can read the height of the document and report it back to the native app so that it can render the webview at the correct height. We may also want to use a mutation observer to monitor for changes.

Communicating JS -> Native is not supported by React Native's `WebView` component, so we'll likely have to extend it to add this feature.

**Comment by arcturus** [comment]
Closed by #65
