### ISSUE TITLE
Add a initial test-suite

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#5]
We will have JS, Java and Objective-C code that will all need testing. Some exploration needs to be done on how others are testing their ReactNative code bases.

**Comment by wilsonpage** [comment]
Good article on testing the JS code:  https://medium.com/@jcfrancisco/unit-testing-react-native-components-a-firsthand-guide-cea561df242b#.3ro4r9v3f

**Comment by wilsonpage** [comment]
https://github.com/mozilla-magnet/magnet-client/pull/72 adds a few more tests and migrates over to Mocha, Sinon, Enzyme architecture. This is following pain I experienced trying to use Jest, due to lack of docs/examples relating to react-native and struggling to find a clean way to get references to mocked dependency instances.

In my exploration I read several articles criticising Jest and very few (excluding FB) praising it. Authors claimed auto-mocking was a testing anti-pattern, forcing you to write functional mocks for each of a module's dependencies, and thus tying unit-tests to private implementation details.

A Mocha/Sinon setup on the other hand allows you to only stub dependencies that you need to control/observe in order to simulate usage. You can largely ignore most of a module's other dependencies. This removes workload and required understanding and should make test more resilient to code refactor.

**Comment by samgiles** [comment]
Thanks for the analysis!

**Comment by samgiles** [comment]
I think this is done - we now have unit tests running on each commit.  We can open further issues to discuss running iOS and Android native tests.

**Comment by samgiles** [comment]
Follow up for native code in #78 and #79
