### ISSUE TITLE
Can't build Android project locally

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#59]
Some [changes](https://github.com/mozilla-magnet/magnet/commit/c563c4699dea8e4020c10e5991bcf2e16d8ac070#diff-dc46f9f5dfe204e394fb41395ccd03cf) made to the `build.gradle` file depend on some constants defined by Travis build scripts. This is causing local (non-travis) builds to fail.

Removing [these lines](https://github.com/mozilla-magnet/magnet/blob/c563c4699dea8e4020c10e5991bcf2e16d8ac070/android/app/build.gradle#L94-L101) and [this line](https://github.com/mozilla-magnet/magnet/blob/c563c4699dea8e4020c10e5991bcf2e16d8ac070/android/app/build.gradle#L115) seem to be a temporary fix.

**Comment by samgiles** [comment]
@wilsonpage how are you building locally?

**Comment by wilsonpage** [comment]
From either Android Studio or `react-native run-android`

**Comment by wilsonpage** [comment]
Oops, accidentally closed.
