### ISSUE TITLE
Provide downloadable builds for iOS

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-client#60]

**Comment by oteo** [comment]
I am assigning to Francisco as I think he's developing/testing the iOS environment. 
@arcturus , let me know if I am wrong and if we need something else from Steffan

**Comment by arcturus** [comment]
We have now builds in testflight. They are not downloadable, but if you install the testflight app and ping me your apple id used on your iphone i can add you to the list of testers.
