### ISSUE TITLE
Android - There is not a message to activate bluetooth when launching the app

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#68]
If Bluetooth is disabled, the app opens but do not ask to enable it, so it only shows a white screen
Used android 5.1.1 and latest release (may 7th)

**Comment by arcturus** [comment]
@isabelrios do you have an ios device to check this out? We can add your apple id to the testflight server to receive the latest build.

**Comment by isabelrios** [comment]
@arcturus Unfortunatelly I do not have an iphone, just an ipad, if that would work sure I will give you my appleId.

**Comment by arcturus** [comment]
mmm not sure yet if it will work on ipad xD, don't think so

**Comment by oteo** [comment]
I have tested with iOS app (via test flight) and after switching BT off and opening Magnet app, a message pops up saying "Turn On Bluetooth to allow Magnet to connect to Accessories" so it seems that it works
