### ISSUE TITLE
Travis nightly builds failing

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#81]
https://travis-ci.org/mozilla-magnet/magnet-client/builds/129906682

**Comment by samgiles** [comment]
Hmm, this is why we need builds on PR.  Seems like a regression. But, they're not reliable enough :/

**Comment by wilsonpage** [comment]
@samgiles can this be closed now?

**Comment by samgiles** [comment]
No - they're no longer failing but I noticed they're not being uploaded anymore.

**Comment by samgiles** [comment]
Ok, fixed now :)
