### ISSUE TITLE
Some urls fails to be showed in magnet

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-client#82]
Some urls don't appear in magnet, despite the metadata server has information.

Example of this is the infamous:
hola.es

**Comment by oteo** [comment]
hahaha, yeah, it's  infamous... but it's short to enter ;)

**Comment by wilsonpage** [comment]
Never heard of it, so you're in the clear :)

**Comment by isabelrios** [comment]
Could it be that the url was not set correctly (which would be like [issue 70](https://github.com/mozilla-magnet/magnet-client/issues/70) or it has been solved recently...I can see it, although not completely correct
I used both beacon and pc broadcasting: http://www.hola.es
![screenshot_2016-05-13-17-13-12](https://cloud.githubusercontent.com/assets/1897507/15252883/2bd92b76-1930-11e6-96bc-57c7378c505d.png)

**Comment by wilsonpage** [comment]
@oteo `http://www.hola.es` is working for me too. Were there any other URLs you were having issue with? Closing until we find a reproducible failing URL.
