### ISSUE TITLE
Should we explore fetching/parsing URL content on the client?

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#9]
I've given this some thought and I think there are compelling reasons to fetch URL content from the client.
1. It scales. A central service could quickly become a bottlekneck.
2. We need client-side fetching/parsing anyway for LAN URLs unreachable from the cloud.
3. We reduce the number of projects the Magnet experience depends on.

IIRC the primary reasons for having a centralised metadata-service are:
1. Anonymity 
2. Caching
3. Global blacklist
4. Batching requests
### Anonymity

If this is important we can send requests via a proxy server to conceal the users IP address.
### Caching

I'm not confident we'll gain much by caching. Each user is in a completely different part of the world discover URLs that are relevant to their location. It is highly unlikely that two Magnet users will be fetching the same URL within a given TTL period.
### Global blacklist

We can still maintain a global blacklist that can be downloaded periodically to the user's device, or alternatively live in our dump proxy server.
### Batching requests

Our job is to render rich content. This involves sending requests for HTML, CSS, JS and images for each URL discovered. Initially batching requests for discovered URLs will reduce the number of overall requests by a very small percentage; I'd argue it's not worth it.

If it can be proven to be worth it performance wise, I'd suggest we add it as a feature to our dump proxy server.

---

Let's discuss :smile:

**Comment by wilsonpage** [comment]
@arcturus can you add you feedback here for reference?

**Comment by arcturus** [comment]
Yes, happy to add more thoughts:
- Regarding caching, I really believe that will improve a lot the experience. Taking into account current scenarios where the physical web have been deployed (conferences, events, etc.) it's likely that we will have a set of users that will be targeted by the same beacons. Think on the workweek in London, with potentiall 1000 mozillians being surronded by 30 beacons.
- A black list in the client side will never work. It won't scale, we cannot control when those list are updated (currently there is a really complex mechanism for Firefox Desktop), it won't be fast enough to update. Also a black list can be huge. I'll push the two projects related to black list that I did during my parental leave :P
- Batching is always nice to have isn't?

**Comment by wilsonpage** [comment]
Closing this for now. May reopen to discuss further if we uncover issues with metadata-service.
